[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "russian_docs_ocr"
dynamic = ["version"]
authors = [
    {name = "Митянина Анастасия Владимировна", email = "av.mityanina@zbrsk.ru"},
    {name = "Мельников Виталий Андреевич", email = "protei300@gmail.com"},
    {name = "Валуев Дмитрий Валерьевич", email = "dee-mon@mail.ru"},
    {name = "Карпич Александр Владимирович", email = "avkarpich@gmail.com"},
    {name = "Вохминцев Александр Владиславович", email = "vav@csu.ru"},
]
description = "Библиотека распознавания документов РФ"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["ocr", "russian", "documents", "rus", "russian_docs_ocr"]
license = {text = "Apache License 2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]
dependencies = [
    "matplotlib==3.11.0",
    "numpy==2.4.6",
    "py_cpuinfo==9.0.0",
    "PyYAML==6.0.3",
    "scikit_learn==1.9.0",
    "tqdm==4.68.3",
    "opencv-contrib-python==4.13.0.92",
    "pandas==3.0.3",
    "Pillow==12.2.0",
    "onnxruntime-gpu==1.27.0",
    "openvino==2026.2.1",
]

[project.optional-dependencies]
dev = [
    "pytest==9.1.1"
]

[project.urls]
Documentation = "https://github.com/protei300/RussianDocsOCR"
repository = "https://github.com/protei300/RussianDocsOCR"

[project.scripts]
russian_docs_ocr_procvess_video = "russian_docs_ocr.scripts.process_video:main"
russian_docs_ocr_procvess_image = "russian_docs_ocr.scripts.process_img:main"
russian_docs_ocr_patches = "russian_docs_ocr.scripts.ocr_patches:main"
russian_docs_ocr_benchmark = "russian_docs_ocr.scripts.benchmark:main"

[tool.hatch.version]
path = "russian_docs_ocr/document_processing/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = [
    "russian_docs_ocr/tests",
    "russian_docs_ocr/scripts/bench_results"
]
include = [
    "russian_docs_ocr/document_processing",
    "russian_docs_ocr/scripts",
]

[tool.hatch.build.targets.wheel]
packages = ["russian_docs_ocr"]

[tool.flake8]
max-line-length = 80
exclude = [
    "russian_docs_ocr/tests"
]