DocDetector: models\Borders
TextFieldsDetector: models\TextFields
AddressLinesDetector: models\AddressLines
AddressTextKindClassifier: models\AddressTextKind
DocTypeAngles: models\DocTypeAngles
Blur: models\Blur
Glare: models\Glare
LCDSpoofing: models\LCDSpoofing
PrintSpoofing: models\PrintSpoofing
WordsDetector: models\Words
OCREngNums: models\OCR\eng+nums
OCRRus: models\OCR\rus
